# scripts/fluent_venturi_auto.py
# -*- coding: utf-8 -*-
"""
文丘里管水肥两相流 Fluent 自动化辅助脚本
================================================

作用
----
1. 根据已经划分好网格/已经保存好的 Fluent case，自动生成 Fluent journal 文件；
2. 可选调用本机 fluent 命令行执行 journal；
3. 自动创建结果目录，保存 case/data 和后处理截图命令模板。

重要说明
--------
本脚本从 Fluent Setup 阶段开始自动化，不负责 SpaceClaim/Workbench 中的几何导入和网格划分。
运行前需要保证 Fluent 中已经有以下边界名称：

    water_inlet
    fertilizer_inlet
    outlet
    wall

推荐流程：
    STL/STEP 导入 ANSYS Workbench
        -> Geometry/SpaceClaim 命名边界
        -> Mesh 生成网格
        -> 保存为 .msh.h5 或 .cas.h5
        -> 用本脚本生成并运行 journal

Windows 示例
------------
只生成 journal，不启动 Fluent：
    python scripts/fluent_venturi_auto.py --input D:\case\venturi.msh.h5

生成 journal 并启动 Fluent：
    python scripts/fluent_venturi_auto.py --input D:\case\venturi.msh.h5 --run --cores 8

如果 fluent 不在 PATH 中：
    python scripts/fluent_venturi_auto.py --input D:\case\venturi.msh.h5 --run --fluent-cmd "C:\Program Files\ANSYS Inc\v232\fluent\ntbin\win64\fluent.exe"

备注
----
Fluent 的 TUI 命令在不同版本中可能略有差异。
如果 journal 在某一步报错，把 Fluent 控制台报错发给我，再按你的版本调整命令。
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def qpath(path: Path) -> str:
    """Return Fluent-friendly quoted path."""
    return str(path.resolve()).replace("\\", "/")


def detect_input_kind(path: Path) -> str:
    name = path.name.lower()
    if name.endswith((".cas", ".cas.h5")):
        return "case"
    if name.endswith((".dat", ".dat.h5")):
        return "data"
    if name.endswith((".msh", ".msh.h5")):
        return "mesh"
    raise ValueError(f"无法识别输入文件类型: {path}")


def make_journal(args: argparse.Namespace, run_dir: Path) -> str:
    input_path = Path(args.input).resolve()
    input_kind = detect_input_kind(input_path)

    case_out = run_dir / "venturi_mixer_setup.cas.h5"
    data_out = run_dir / "venturi_mixer_result.dat.h5"

    if input_kind == "case":
        read_cmd = f'/file/read-case "{qpath(input_path)}"'
    elif input_kind == "mesh":
        read_cmd = f'/file/read-mesh "{qpath(input_path)}"'
    else:
        # data usually needs a paired case, so we do not accept it directly.
        raise ValueError("请传入 .msh/.msh.h5 或 .cas/.cas.h5，不要直接传 .dat 文件。")

    scale_block = ""
    if args.scale_mm_to_m:
        scale_block = """
; 如果你的网格坐标被 Fluent 识别为 mm 尺寸，可启用 0.001 缩放到 m。
; 注意：只在确认 Fluent 尺寸确实大了 1000 倍时使用。
/mesh/scale 0.001 0.001 0.001
"""

    # Fluent TUI journal. Some prompts may be version-dependent; keep commands separated and commented.
    journal = f"""
; ============================================================
; Venturi fertilizer mixer Fluent journal
; Generated by scripts/fluent_venturi_auto.py
; Created at: {datetime.now().isoformat(timespec='seconds')}
; ============================================================

{read_cmd}
/mesh/check
{scale_block}
; -----------------------------
; General solver setting
; -----------------------------
/define/models/solver/pressure-based yes
/define/models/unsteady-2nd-order? yes

; -----------------------------
; Multiphase and turbulence model
; VOF, 2 phases: water + liquid_fertilizer
; 如果此处因 Fluent 版本不同报错，可在 GUI 中手动设置：模型 -> 多相流 -> VOF -> 相数 2
; -----------------------------
/define/models/multiphase/vof yes 2 no

; Realizable k-epsilon turbulence model.
; 如果报错，可在 GUI 中手动设置：模型 -> 粘性 -> k-epsilon -> Realizable
/define/models/viscous/ke-realizable yes

; -----------------------------
; Materials
; water-liquid normally already exists in Fluent database.
; liquid_fertilizer: rho={args.fertilizer_density} kg/m3, mu={args.fertilizer_viscosity} kg/(m s)
; 如果材料命令报错，可在 GUI 中手动新建 liquid_fertilizer。
; -----------------------------
/define/materials/change-create liquid_fertilizer liquid_fertilizer yes constant {args.fertilizer_density} yes constant {args.fertilizer_viscosity}

; -----------------------------
; Phase materials
; 注意：不同 Fluent 版本的 phase TUI 命令差异较大。
; 若下面几行报错，请在 GUI 中设置：相 -> 主相 water-liquid，次相 liquid_fertilizer。
; -----------------------------
; /define/phases/set-domain-properties mixture yes water-liquid liquid_fertilizer

; -----------------------------
; Boundary conditions
; 需要已有命名边界：water_inlet、fertilizer_inlet、outlet、wall
; water_inlet: velocity-inlet {args.water_velocity} m/s, fertilizer volume fraction 0
; fertilizer_inlet: velocity-inlet {args.fertilizer_velocity} m/s, fertilizer volume fraction 1
; outlet: pressure-outlet {args.outlet_pressure} Pa gauge
; -----------------------------
/define/boundary-conditions/zone-type water_inlet velocity-inlet
/define/boundary-conditions/velocity-inlet water_inlet yes no {args.water_velocity} no 0 no 0 no 0 no 0 no 1

/define/boundary-conditions/zone-type fertilizer_inlet velocity-inlet
/define/boundary-conditions/velocity-inlet fertilizer_inlet yes no {args.fertilizer_velocity} no 0 no 0 no 0 no 0 no 1

/define/boundary-conditions/zone-type outlet pressure-outlet
/define/boundary-conditions/pressure-outlet outlet yes no {args.outlet_pressure} no 0 no 0 no 1

; -----------------------------
; Solution methods
; -----------------------------
/solve/set/p-v-coupling 20
/solve/set/discretization-scheme/pressure 14
/solve/set/discretization-scheme/mom 1
/solve/set/discretization-scheme/k 1
/solve/set/discretization-scheme/epsilon 1

; -----------------------------
; Initialization and calculation
; -----------------------------
/solve/initialize/hyb-initialization
/file/write-case "{qpath(case_out)}"

/solve/set/time-step {args.dt}
/solve/dual-time-iterate {args.steps} {args.iter_per_step}

/file/write-data "{qpath(data_out)}"
/file/write-case-data "{qpath(run_dir / 'venturi_mixer_final.cas.h5')}"

; -----------------------------
; End
; -----------------------------
/exit yes
""".strip()

    return journal


def write_readme(args: argparse.Namespace, run_dir: Path) -> None:
    text = f"""# Venturi Fluent 自动化运行记录

输入文件：{args.input}
创建时间：{datetime.now().isoformat(timespec='seconds')}

## 关键参数

- 清水入口 water_inlet：{args.water_velocity} m/s
- 肥液入口 fertilizer_inlet：{args.fertilizer_velocity} m/s
- 出口 outlet：{args.outlet_pressure} Pa 表压
- 肥液密度：{args.fertilizer_density} kg/m3
- 肥液动力粘度：{args.fertilizer_viscosity} kg/(m s)
- 时间步长：{args.dt} s
- 时间步数：{args.steps}
- 每步最大迭代次数：{args.iter_per_step}

## 前置条件

Fluent case/mesh 中必须存在以下边界：

- water_inlet
- fertilizer_inlet
- outlet
- wall

## 重要提醒

Fluent TUI 命令在不同版本中可能略有差异。如果 journal 报错，不代表模型不能算，
通常只需要在 GUI 中手动补充报错对应的设置。

优先检查：

1. 边界名称是否传入 Fluent；
2. VOF 两相是否成功启用；
3. 主相是否为 water-liquid；
4. 次相是否为 liquid_fertilizer；
5. 两个入口的体积分数是否正确。
"""
    (run_dir / "README_venturi_fluent_run.md").write_text(text, encoding="utf-8")


def run_fluent(args: argparse.Namespace, journal_path: Path, run_dir: Path) -> int:
    fluent_cmd = args.fluent_cmd
    dim = "3ddp" if args.double_precision else "3d"
    cmd = [fluent_cmd, dim, f"-t{args.cores}", "-i", str(journal_path)]

    print("\n启动 Fluent：")
    print(" ".join(cmd))
    print(f"工作目录：{run_dir}\n")

    try:
        return subprocess.run(cmd, cwd=run_dir).returncode
    except FileNotFoundError:
        print("[ERROR] 找不到 fluent 命令。")
        print("解决方法：")
        print("1. 把 Fluent 加入系统 PATH；或")
        print("2. 使用 --fluent-cmd 指定 fluent.exe 完整路径。")
        return 127


def main() -> int:
    parser = argparse.ArgumentParser(description="生成并可选运行文丘里管水肥混合 Fluent 自动化 journal。")

    parser.add_argument("--input", required=True, help="Workbench/Fluent 导出的 .msh.h5 或 .cas.h5 文件")
    parser.add_argument("--out-dir", default=None, help="输出目录，默认 results/fluent_venturi/<时间戳>")

    parser.add_argument("--water-velocity", type=float, default=1.5, help="清水入口速度 m/s")
    parser.add_argument("--fertilizer-velocity", type=float, default=1.0, help="肥液入口速度 m/s")
    parser.add_argument("--outlet-pressure", type=float, default=0.0, help="出口表压 Pa")

    parser.add_argument("--fertilizer-density", type=float, default=1050.0, help="肥液密度 kg/m3")
    parser.add_argument("--fertilizer-viscosity", type=float, default=0.00113, help="肥液动力粘度 kg/(m s)")

    parser.add_argument("--dt", type=float, default=0.001, help="瞬态时间步长 s")
    parser.add_argument("--steps", type=int, default=2000, help="时间步数")
    parser.add_argument("--iter-per-step", type=int, default=20, help="每个时间步最大迭代次数")

    parser.add_argument("--scale-mm-to-m", action="store_true", help="把网格坐标缩小 1000 倍，仅在 Fluent 尺寸单位错误时使用")

    parser.add_argument("--run", action="store_true", help="生成 journal 后直接调用 Fluent 运行")
    parser.add_argument("--fluent-cmd", default="fluent", help="fluent 命令或 fluent.exe 完整路径")
    parser.add_argument("--cores", type=int, default=4, help="Fluent 并行核心数")
    parser.add_argument("--double-precision", action="store_true", default=True, help="使用双精度 3ddp")

    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"[ERROR] 输入文件不存在: {input_path}")
        return 2

    if args.out_dir:
        run_dir = Path(args.out_dir).resolve()
    else:
        run_id = datetime.now().strftime("%Y%m%d_%H%M%S")
        run_dir = ROOT / "results" / "fluent_venturi" / run_id

    run_dir.mkdir(parents=True, exist_ok=True)

    journal_text = make_journal(args, run_dir)
    journal_path = run_dir / "venturi_fluent_setup.jou"
    journal_path.write_text(journal_text, encoding="utf-8")
    write_readme(args, run_dir)

    print("=" * 70)
    print("Fluent 自动化文件已生成")
    print(f"运行目录: {run_dir}")
    print(f"Journal : {journal_path}")
    print("=" * 70)

    if not args.run:
        print("\n未启动 Fluent。手动运行方式：")
        print(f"fluent 3ddp -t{args.cores} -i \"{journal_path}\"")
        return 0

    return run_fluent(args, journal_path, run_dir)


if __name__ == "__main__":
    raise SystemExit(main())
